httpPort: 8090
grpcPort: 8091
imageFolder: ./images/
grpcEndPoint: flair-engine-grpc:6565
FlairBiEndPoint: http://localhost:8002
discovery:
  eureka:
    url: ''
ssl:
  enabled: false
  caCert: certs/trustCertCollectionFile.crt
  serverCert: certs/certChainFile.crt
  serverKey: certs/privateKeyFile.key
mailService:
  serive: gmail
  sender: admin-vizcentric@gmail.com
  testUser: admin@vizcentric.com
  auth :
    user: vizcentric.smtp@gmail.com
    pass:
