grpc:
  port: 6565
  tls:
    enabled: ${GRPC_SSL_ENABLED:false}
    certificate: server.crt
    key: server.pem

eureka:
    instance:
        # appname: flair-engine-grpc
        # virtualHostName: flair-engine-grpc
        # instanceId: ${spring.cloud.client.hostname}:flair-engine-grpc:${spring.application.instance-id:${random.value}}
        nonSecurePort: ${grpc.port}
        securePort: ${grpc.port}
        securePortEnabled: true

